# Generated by Django 3.2.9 on 2021-11-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='user_name',
        ),
    ]
