# Generated by Django 3.2.9 on 2021-11-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userbase_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='email',
            new_name='user_name',
        ),
    ]
