# Generated by Django 3.2.9 on 2021-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_first_name_userbase_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='about',
        ),
        migrations.AlterField(
            model_name='userbase',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
