# Generated by Django 3.2.9 on 2021-11-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211130_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='full_name',
        ),
    ]
