# Generated by Django 3.2.9 on 2021-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userbase_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
