# Generated by Django 3.2.9 on 2021-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211202_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Category Name'), max_length=255, unique=True, verbose_name='Category safe URL'),
        ),
    ]
