# Generated by Django 3.2.9 on 2021-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Product Type'),
        ),
    ]
